# Generated by Django 5.1.2 on 2024-10-20 18:56

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amenity',
            name='preferences',
        ),
        migrations.RemoveField(
            model_name='beveragepreference',
            name='preferences',
        ),
        migrations.RemoveField(
            model_name='nonalcoholicbeverage',
            name='beverage_preference',
        ),
        migrations.RemoveField(
            model_name='dietaryrestriction',
            name='food_preference',
        ),
        migrations.RemoveField(
            model_name='favoritefood',
            name='food_preference',
        ),
        migrations.RemoveField(
            model_name='foodpreference',
            name='preferences',
        ),
        migrations.RemoveField(
            model_name='pillowtype',
            name='preferences',
        ),
        migrations.RemoveField(
            model_name='roomlocation',
            name='preferences',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='guest',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='is_past',
        ),
        migrations.RemoveField(
            model_name='preferences',
            name='guest',
        ),
        migrations.AddField(
            model_name='guest',
            name='past_bookings',
            field=models.ManyToManyField(related_name='past_guests', to='api.booking'),
        ),
        migrations.AddField(
            model_name='guest',
            name='preferences',
            field=models.OneToOneField(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='api.preferences'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guest',
            name='upcoming_bookings',
            field=models.ManyToManyField(related_name='upcoming_guests', to='api.booking'),
        ),
        migrations.AddField(
            model_name='preferences',
            name='amenities',
            field=models.JSONField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preferences',
            name='beverages',
            field=models.JSONField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preferences',
            name='food_preferences',
            field=models.JSONField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preferences',
            name='pillow_type',
            field=models.JSONField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preferences',
            name='room_location',
            field=models.JSONField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='number_of_guests',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='number_of_rooms',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='guest',
            name='bonvoy_id',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='guest',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='guest',
            name='gender',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='guest',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='AlcoholicBeverage',
        ),
        migrations.DeleteModel(
            name='Amenity',
        ),
        migrations.DeleteModel(
            name='BeveragePreference',
        ),
        migrations.DeleteModel(
            name='NonAlcoholicBeverage',
        ),
        migrations.DeleteModel(
            name='DietaryRestriction',
        ),
        migrations.DeleteModel(
            name='FavoriteFood',
        ),
        migrations.DeleteModel(
            name='FoodPreference',
        ),
        migrations.DeleteModel(
            name='PillowType',
        ),
        migrations.DeleteModel(
            name='RoomLocation',
        ),
    ]
