# Generated by Django 5.1.2 on 2024-10-20 02:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BeveragePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='FoodPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('birthday', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('bonvoy_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='AlcoholicBeverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('beverage_preference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alcoholic', to='api.beveragepreference')),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('food_preference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='api.foodpreference')),
            ],
        ),
        migrations.CreateModel(
            name='DietaryRestriction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('food_preference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dietary_restrictions', to='api.foodpreference')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('hotel', models.CharField(max_length=100)),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('number_of_rooms', models.PositiveIntegerField()),
                ('number_of_guests', models.PositiveIntegerField()),
                ('is_past', models.BooleanField(default=False)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='api.guest')),
            ],
        ),
        migrations.CreateModel(
            name='NonAlcoholicBeverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('beverage_preference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='non_alcoholic', to='api.beveragepreference')),
            ],
        ),
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessible', models.BooleanField(default=False)),
                ('bed_type', models.CharField(max_length=50)),
                ('room_type', models.CharField(max_length=50)),
                ('room_temperature', models.IntegerField()),
                ('prompt_priority', models.CharField(max_length=50)),
                ('guest', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='api.guest')),
            ],
        ),
        migrations.CreateModel(
            name='PillowType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('preferences', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pillow_types', to='api.preferences')),
            ],
        ),
        migrations.AddField(
            model_name='foodpreference',
            name='preferences',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='food_preferences', to='api.preferences'),
        ),
        migrations.AddField(
            model_name='beveragepreference',
            name='preferences',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='beverage_preferences', to='api.preferences'),
        ),
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('preferences', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='api.preferences')),
            ],
        ),
        migrations.CreateModel(
            name='RoomLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50)),
                ('preferences', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_locations', to='api.preferences')),
            ],
        ),
    ]
